spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: atmdev
    password: atmdev123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ALWAYS
