spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:./src/main/resources/db-data;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driver-class-name: org.h2.Driver